name:           kmer-find
version:        0.0.0
synopsis:       BLAST-like kmer large scale searching
category:       Bioinformatics
license:        GPL-3
maintainer:     Luis Pedro Coelho <coelho@embl.de>
ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -fwarn-tabs
    - -rtsopts
    - ! '"-with-rtsopts=-A64m -n4m -H"'

dependencies:
  - base >= 4.7 && < 5
  - binary
  - bytestring
  - conduit
  - conduit-extra
  - conduit-combinators
  - conduit-algorithms
  - deepseq
  - directory
  - extra
  - mmap
  - temporary
  - safeio
  - vector


source-dirs:
  - ./src

executables:
  Query:
    main: Query.hs
    other-modules: []
  EncodeKmers:
    main: EncodeKmers.hs
    other-modules: []
  BuildIndex2:
    main: BuildIndex2.hs
    other-modules: []
