name:           kmer-find
version:        0.0.0
synopsis:       BLAST-like kmer large scale searching
category:       Bioinformatics
license:        GPL-3
maintainer:     Luis Pedro Coelho <coelho@embl.de>
ghc-options:    -Wall -O2 -threaded -fwarn-tabs

dependencies:
  - base >= 4.7 && < 5
  - async
  - binary
  - binary-conduit
  - bytestring
  - conduit
  - conduit-extra
  - conduit-combinators
  - conduit-algorithms
  - containers
  - data-hash
  - deepseq
  - directory
  - diskhash
  - exceptions
  - extra
  - filepath
  - filemanip
  - hashtables
  - primitive
  - mmap
  - MissingH
  - resourcet
  - temporary
  - text
  - transformers
  - transformers-base
  - safe
  - safeio
  - strict
  - stringsearch
  - vector
  - vector-algorithms


source-dirs:
  - ./src

executables:
  Query:
    main: Query.hs
  EncodeKmers:
    main: EncodeKmers.hs
  BuildIndex1:
    main: BuildIndex1.hs
  BuildIndex2:
    main: BuildIndex2.hs
